development:
  adapter: postgresql
  encoding: unicode
  username: user100
  password: Password100
  database: nov9part3pass_dev
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  username: user100
  password: Password100
  database: nov9part3pass_test
  port: 5432

  production:
    adapter: postgres
    database: nov9part3pass_production
    username:
    password:
